import React, { ComponentProps, CSSProperties } from 'react';
import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { useTranslation } from 'react-i18next';
import {
  SidebarRowDragSource,
  SidebarRowKeyboardDragHandle,
} from '../../components/sidebar/Sidebar.css';
import { animateSortableLayoutDuringDrag } from '../../utils/sortableDrag';
import { RoomNavItem } from './RoomNavItem';

export type SortableRoomNavItemData = {
  roomId: string;
  parentSpaceId: string;
};

export const makeRoomSortableId = (groupId: string, roomId: string): string =>
  JSON.stringify([groupId, roomId]);

export const parseRoomSortableId = (sortableId: string): SortableRoomNavItemData | undefined => {
  try {
    const value: unknown = JSON.parse(sortableId);
    if (
      Array.isArray(value) &&
      value.length === 2 &&
      typeof value[0] === 'string' &&
      value[0] &&
      typeof value[1] === 'string' &&
      value[1]
    ) {
      return { parentSpaceId: value[0], roomId: value[1] };
    }
  } catch {
    // Fall back to IDs generated by older mounted clients during hot reload.
  }

  const separatorIndex = sortableId.indexOf('::');
  if (separatorIndex <= 0) return undefined;

  return {
    parentSpaceId: sortableId.slice(0, separatorIndex),
    roomId: sortableId.slice(separatorIndex + 2),
  };
};

type SortableRoomNavItemProps = ComponentProps<typeof RoomNavItem> & {
  parentSpaceId: string;
  disabled?: boolean;
};

type SortableRoomNavItemContainerProps = {
  groupId: string;
  roomId: string;
  data?: Record<string, unknown>;
  disabled?: boolean;
  dragLabel: string;
  children: React.ReactNode;
};

const sortableStyle = (
  transform: ReturnType<typeof useSortable>['transform'],
  transition: ReturnType<typeof useSortable>['transition'],
  dragging: boolean
): CSSProperties => ({
  transform: CSS.Transform.toString(transform),
  transition,
  opacity: dragging ? 0.45 : undefined,
});

export function SortableRoomNavItemContainer({
  groupId,
  roomId,
  data,
  disabled,
  dragLabel,
  children,
}: SortableRoomNavItemContainerProps) {
  const {
    attributes,
    listeners,
    setActivatorNodeRef,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({
    id: makeRoomSortableId(groupId, roomId),
    disabled,
    animateLayoutChanges: animateSortableLayoutDuringDrag,
    data: {
      ...data,
      roomId,
      parentSpaceId: groupId,
    } satisfies SortableRoomNavItemData,
  });

  const { onKeyDown, ...pointerListeners } = listeners ?? {};

  const stopPointerActivation = (evt: React.SyntheticEvent<HTMLElement>) => {
    if (
      (evt.target as HTMLElement).closest('button, input, textarea, select, [data-no-room-drag]')
    ) {
      evt.stopPropagation();
    }
  };

  const stopKeyboardActivation = (evt: React.SyntheticEvent<HTMLElement>) => {
    if (
      evt.target !== evt.currentTarget &&
      (evt.target as HTMLElement).closest('a, button, input, textarea, select, [data-no-room-drag]')
    ) {
      evt.stopPropagation();
    }
  };

  return (
    <div
      ref={(node) => {
        setNodeRef(node);
      }}
      className={SidebarRowDragSource}
      style={sortableStyle(transform, transition, isDragging)}
      data-room-id={roomId}
      onPointerDownCapture={(evt) => {
        setActivatorNodeRef(evt.currentTarget);
        stopPointerActivation(evt);
      }}
      onMouseDownCapture={(evt) => {
        setActivatorNodeRef(evt.currentTarget);
        stopPointerActivation(evt);
      }}
      onTouchStartCapture={(evt) => {
        setActivatorNodeRef(evt.currentTarget);
        stopPointerActivation(evt);
      }}
      {...pointerListeners}
    >
      {!disabled && (
        <button
          ref={setActivatorNodeRef}
          type="button"
          className={SidebarRowKeyboardDragHandle}
          aria-label={dragLabel}
          data-no-room-drag
          onKeyDownCapture={stopKeyboardActivation}
          onKeyDown={(event) => onKeyDown?.(event)}
          {...attributes}
        >
          {dragLabel}
        </button>
      )}
      {children}
    </div>
  );
}

export function SortableRoomNavItem({
  parentSpaceId,
  room,
  disabled,
  ...props
}: SortableRoomNavItemProps) {
  const { t } = useTranslation();
  return (
    <SortableRoomNavItemContainer
      groupId={parentSpaceId}
      roomId={room.roomId}
      disabled={disabled}
      dragLabel={t('nav.dragRoom', { room: room.name })}
    >
      <RoomNavItem room={room} {...props} />
    </SortableRoomNavItemContainer>
  );
}
