name: NPM Lockfile Changes

on:
  pull_request:
    paths:
      - 'package-lock.json'

jobs:
  lockfile_changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.node-version'
          package-manager-cache: false
      - name: Validate npm lockfile
        run: npm ci --ignore-scripts
